// <auto-generated />
using System;
using CanvasAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CanvasAPI.Migrations
{
    [DbContext(typeof(AppDatabase))]
    [Migration("20200915024813_InitialMigration-2")]
    partial class InitialMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CanvasAPI.Models.Canvas", b =>
                {
                    b.Property<int>("CanvasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CanvasID");

                    b.ToTable("Canvas");
                });

            modelBuilder.Entity("CanvasAPI.Models.ColorData", b =>
                {
                    b.Property<int>("ColorDataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CanvasID")
                        .HasColumnType("int");

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("int");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.HasKey("ColorDataID");

                    b.HasIndex("CanvasID");

                    b.ToTable("ColorData");
                });

            modelBuilder.Entity("CanvasAPI.Models.Poll", b =>
                {
                    b.Property<int>("Poll_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pool_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Poll_ID");

                    b.ToTable("Poll");
                });

            modelBuilder.Entity("CanvasAPI.Models.PollOption", b =>
                {
                    b.Property<int>("Option_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Poll_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Poll_ID1")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Option_ID");

                    b.HasIndex("Poll_ID1");

                    b.ToTable("PollOption");
                });

            modelBuilder.Entity("CanvasAPI.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("User_ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CanvasAPI.Models.Vote", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Poll_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Poll_ID1")
                        .HasColumnType("int");

                    b.Property<int?>("User_ID1")
                        .HasColumnType("int");

                    b.HasKey("User_ID");

                    b.HasIndex("Poll_ID1");

                    b.HasIndex("User_ID1");

                    b.ToTable("Vote");
                });

            modelBuilder.Entity("phase_2_back_end.Models.HistoricalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HistoricalData");
                });

            modelBuilder.Entity("CanvasAPI.Models.ColorData", b =>
                {
                    b.HasOne("CanvasAPI.Models.Canvas", null)
                        .WithMany("ColorData")
                        .HasForeignKey("CanvasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CanvasAPI.Models.PollOption", b =>
                {
                    b.HasOne("CanvasAPI.Models.Poll", null)
                        .WithMany("PollOption")
                        .HasForeignKey("Poll_ID1");
                });

            modelBuilder.Entity("CanvasAPI.Models.Vote", b =>
                {
                    b.HasOne("CanvasAPI.Models.Poll", null)
                        .WithMany("Vote")
                        .HasForeignKey("Poll_ID1");

                    b.HasOne("CanvasAPI.Models.User", null)
                        .WithMany("Vote")
                        .HasForeignKey("User_ID1");
                });
#pragma warning restore 612, 618
        }
    }
}
