// <auto-generated />
using System;
using CanvasAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CanvasAPI.Migrations
{
    [DbContext(typeof(AppDatabase))]
    [Migration("20200915065257_InitialMigration-3")]
    partial class InitialMigration3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CanvasAPI.Models.Poll", b =>
                {
                    b.Property<int>("Poll_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pool_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Poll_ID");

                    b.ToTable("Poll");
                });

            modelBuilder.Entity("CanvasAPI.Models.PollOption", b =>
                {
                    b.Property<int>("Option_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Poll_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Poll_ID1")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Option_ID");

                    b.HasIndex("Poll_ID1");

                    b.ToTable("PollOption");
                });

            modelBuilder.Entity("CanvasAPI.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CanvasAPI.Models.Vote", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Poll_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Poll_ID1")
                        .HasColumnType("int");

                    b.Property<int?>("User_ID1")
                        .HasColumnType("int");

                    b.HasKey("User_ID");

                    b.HasIndex("Poll_ID1");

                    b.HasIndex("User_ID1");

                    b.ToTable("Vote");
                });

            modelBuilder.Entity("CanvasAPI.Models.PollOption", b =>
                {
                    b.HasOne("CanvasAPI.Models.Poll", null)
                        .WithMany("PollOption")
                        .HasForeignKey("Poll_ID1");
                });

            modelBuilder.Entity("CanvasAPI.Models.Vote", b =>
                {
                    b.HasOne("CanvasAPI.Models.Poll", null)
                        .WithMany("Vote")
                        .HasForeignKey("Poll_ID1");

                    b.HasOne("CanvasAPI.Models.User", null)
                        .WithMany("Vote")
                        .HasForeignKey("User_ID1");
                });
#pragma warning restore 612, 618
        }
    }
}
